name: 'Custom Action Demo'
description: 'Prints a custom message in the workflow'
inputs:
  message:
    description: 'The message to print'
    required: true
outputs:
  message:
    description: 'the output message'
runs:
  using: 'node12'
  main: 'action.js'
