name: Custom Action Demo
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Execute Custom Action
        id: custom-action
        uses: .\
        with:
          message: "Hello from your custom action!"
      
      - name: Display Custom Action Output
        run: echo "Custom Action Output:${{ steps.custom-action.outputs.message }}"
